volumes:
  redis_data:
  postgres_data:

networks:
  net:
    driver: bridge

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    env_file: .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    expose:
      - "${REDIS_PORT}"
    volumes:
      - redis_data:${REDIS_DATA}
    networks:
      - net

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${POSTGRES_DATA}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
      - "${POSTGRES_PORT}"
    volumes:
      - postgres_data:${POSTGRES_DATA}
    networks:
      - net

  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile.bot
    restart: unless-stopped
    env_file: .env
    depends_on:
      - redis
      - postgres
    networks:
      - net
